workflows:
  staging-android-workflow:
    name: Android Staging Workflow
    instance_type: mac_mini_m1
    max_build_duration: 20
    environment:
      groups:
        - google_credentials
      flutter: "3.22.2"
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'staging'
          include: true
    
    scripts:
      - name: Setup the keystore
        script: |
          echo $KEYSTORE_FILE | base64 --decode > /tmp/keystore.jks
          cat >> "$CM_BUILD_DIR/android/key.properties" << EOF
          storePassword=$KEYSTORE_PASSWORD
          keyPassword=$KEYSTORE_KEY_PASSWORD
          keyAlias=deployment
          storeFile=/tmp/keystore.jks
          EOF     
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Increment version and build AAB
        script: |
          flutter build appbundle --release
    artifacts:
      - build/**/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: alpha

  staging-ios-workflow:
    name: iOS Staging Workflow
    max_build_duration: 20
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.hakim.edulink
      flutter: "3.22.2"
      xcode: latest 
      vars:
        APP_ID: 6480532854
    cache:
      cache_paths:
        - ~/.pub-cache
    triggering:
      events:
        - pull_request
      branch_patterns:
        - pattern: 'staging'
          include: true
    scripts:
      - name: Use the profile in xcode
        script: |
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Pod install
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Extract version from pubspec.yaml and build IPA
        script: | 
          # Extract version from pubspec.yaml
          VERSION=$(sed -n 's/^version: *//p' pubspec.yaml)
          IFS='+'
          read -ra VERSION_PARTS <<< "$VERSION"
          BUILD_NAME="${VERSION_PARTS[0]}"
          BUILD_NUMBER="${VERSION_PARTS[1]}"
          echo "Build name: $BUILD_NAME"
          echo "Build number: $BUILD_NUMBER"
          
          # Build IPA
          flutter build ipa --release \
            --build-name=$BUILD_NAME \
            --build-number=$BUILD_NUMBER
      - name: Sign IPA with xcode
        script: |
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - build/ios/ipa/*.ipa
    integrations:
      app_store_connect: Codemagic api key
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true