name: edulink_mobile
description: "A new Flutter project."

version: 1.1.0

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  table_calendar:
  intl:
  auto_route:
  get_it:
  shared_preferences:
  dio:
  equatable:
  flutter_dotenv:
  flutter_screenutil:
  dartz:
  flutter_bloc:
  bloc:
  cupertino_icons:
  salomon_bottom_bar:
  pusher_channels_flutter:
  rxdart:
  flutter_svg:
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints:
  auto_route_generator:
  build_runner:
  analyzer:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/edulink_icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
